version: "3"
services:
  fastapi:
    build: .
    ports:
      - 8081:8081
    environment:
      - DB_HOST=${HOST}
    volumes:
      - .:/data
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - db:/bitnami/mongodb
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '8080:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs

volumes:
  db: