version: "3"
services:
  fastapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${HOST}
    volumes:
      - .:/data
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - db:/bitnami/mongodb

volumes:
  db: