services:
  fastapi:
    public: true
    image: Samirelh7/fastapi-crud:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 100m
      memory: 128Mi
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - /bitnami/mongodb